[package]
name = "beers-p2p"
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
## beers
beers-primitives = { workspace = true }

## alloy
alloy-primitives.workspace = true
alloy-signer.workspace = true
alloy-signer-wallet.workspace = true

anyhow.workspace = true
futures.workspace = true
libp2p.workspace = true
libp2p-stream.workspace = true
eyre.workspace = true
prost.workspace = true
prost-types.workspace = true
rand.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
handshake = { path = "../protocols/handshake" }

[build-dependencies]
prost-build = "0.12.6"
