[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.84"
license = "AGPL-3.0"
homepage = "https://nullisyxz.github.io/bee-rs"
repository = "https://nullisxyz.github.io/bee-rs"

[workspace]
members = [
    # "crates/file",
    #"crates/manifest",
    #"crates/postage",
    #"crates/logging",
    # "bin/waku-swarm-relay",
    # "bin/swarm-tools",
    #"bin/bee-rs",
    # "bin/wasm-playground",
    # "bin/swarm-wasm-lib",
    "crates/primitives",
    "crates/primitives-traits",
]
# default-members = [
#     "bin/bee-rs",
#     "bin/waku-swarm-relay",
# ]

# Explicitly set the resolver to version 2, which is the default for packages with edition >= 2021
# https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html
resolver = "2"

[workspace.lints]
rust.unreachable_pub = "warn"

[workspace.dependencies]
## swarm
swarm-primitives = { path = "crates/primitives" }
swarm-primitives-traits = { path = "crates/primitives-traits" }

## alloy
alloy = { version = "0.9.1", features = [
    "eips",
    "full",
    "hyper",
    "json-rpc",
    "node-bindings",
    "rpc-client",
    "rpc-types-debug",
    "rpc-types-trace",
    "signer-keystore",
    "signer-mnemonic",
] }

## misc
clap = { version = "4.5.23", features = ["derive", "env"] }
# chrono = "0.4.39"
criterion = "0.5"
getrandom = "0.2"
# hex = "0.4.3"
# once_cell = "1.20.2"
# serde = { version = "1", features = ["derive"] }
# serde_json = "1"
# serde_with = { version = "3.12.0", features = ["hex"] }
rand = "0.8.5"
thiserror = "2.0.4"
# tracing = "0.1.41"
# tracing-subscriber = { version = "0.3.19", features = [
#     "env-filter",
#     "ansi",
#     "fmt",
#     "std",
#     "json",
#     "time",
# ] }

## tokio
# tokio-stream = "0.1.17"
tokio = { version = "1.42.0", default-features = false, features = [
    "macros",
    "rt",
] }
# tokio-util = { version = "0.7.13", features = ["codec"] }

## async
# async-trait = "0.1"
futures = "0.3"

## wasm
# wasm-bindgen = "0.2.97"
# wasm-bindgen-futures = "0.4.47"
# wasm-bindgen-test = "0.3.47"
# js-sys = "0.3.74"

# dotenv = "0.15.0"
# reqwest = { version = "0.12.9", features = ["json"] }
# async-recursion = "1.1.1"
anyhow = "1.0.94"
# prost = "0.13.4"
