[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.80"
license = "AGPL-3.0"
homepage = "https://rndlabs.github.io/bee-rs"
repository = "https://github.com/rndlabs/bee-rs"
exclude = ["./github/"]

[workspace.lints]

[workspace]
members = [
    # "crates/manifest",
    # "crates/postage",
    # "bin/waku-swarm-relay",
    "bin/swarm-tools",
    "bin/beers",
    "bin/wasm-playground",
    # "bin/swarm-wasm-lib",
    "crates/net/p2p",
    "crates/net/protocols/handshake",
    "crates/net/protocols/pushsync",
    "crates/net/protocols/pullsync",
    "crates/net/protocols/cursors",
    "crates/net/protocols/kad",
    "crates/net/protocols/pseudosettle",
    "crates/net/protocols/retrieval",
    "crates/net/protocols/swap",
    "crates/net/protocols/status",
    "crates/tracing",
    "crates/node-core",
    "crates/cli",
    "crates/tasks",
    "crates/metrics",
    "crates/node/builder",
    "crates/node/api",
    "crates/node/events",
    "crates/primitives",
]
default-members = [
    "bin/beers",
    # "bin/waku-swarm-relay",
]

# Explicitly set the resolver to version 2, which is the default for packages with edition >= 2021
# https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html
resolver = "2"

# Like release, but with full debug symbols. Use for e.g. `perf`.
[profile.debug-fast]
inherits = "release"
debug = true

[profile.maxperf]
inherits = "release"
lto = "fat"
codegen-units = 1
incremental = false

[workspace.dependencies]
# beers
beers-cli-runner = { path = "crates/cli" }
beers-node-core = { path = "crates/node-core" }
beers-primitives = { path = "crates/primitives" }
beers-tasks = { path = "crates/tasks"}
beers-tracing = { path = "crates/tracing" }
beers-metrics = { path = "crates/metrics" }
beers-metrics-derive = { path = "crates/metrics/metrics-derive" }
beers-p2p = { path = "crates/net/p2p"}

## crypto
tiny-keccak = { version = "2.0.2", features = ["keccak"] }

## misc
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "ansi", "fmt", "std", "json", "time"] }
tracing-appender = "0.2"
eyre = "0.6"
thiserror = "1.0.61"
serde_json = "1.0.117"
serde = { version = "1.0.203", features = ["derive"] }
rand = "0.8.5"
hex = "0.4.3"
humantime = "2.1"
humantime-serde = "1.1"


## tokio
tokio-stream = "0.1.15"
tokio = { version = "1.38.0", default-features = false, features = ["macros", "rt", "rt-multi-thread"] }
tokio-util = { version = "0.7.11", features = ["codec"] }

## async
async-trait = "0.1.80"
futures = "0.3.30"
pin-project = "1.0.12"
futures-util = "0.3.30"
tower = "0.4"
tower-http = "0.5"

## wasm
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
wasm-bindgen-test = "0.3.42"
js-sys = "0.3.69"

## protobufs / libp2p
libp2p = { version = "0.54.0", git = "https://github.com/libp2p/rust-libp2p", features = [
    "tokio",
    "autonat",
    "dns",
    "kad",
    "tcp",
    "ping",
    "noise",
    "yamux",
    "ecdsa",
    "identify",
    "macros"
] }
libp2p-stream = { git = "https://github.com/libp2p/rust-libp2p" }
prost = "0.12.6"
prost-types = "0.12.6"

## alloy
alloy-primitives = "0.7.6"
alloy-signer = { git = "https://github.com/alloy-rs/alloy", rev = "00d81d7", default-features = false }
alloy-signer-wallet = { git = "https://github.com/alloy-rs/alloy", rev = "00d81d7", default-features = false }

clap = { version = "4.5.6", features = ["derive", "env"] }
chrono = "0.4.38"
dotenv = "0.15.0"
serde_with = { version = "3.8.1", features = ["hex"] }
reqwest = { version = "0.12.4", features = ["json", "rustls-tls"] }
async-recursion = "1.1.1"
anyhow = "1.0.86"
once_cell = "1.19.0"
syn = "2.0"
dyn-clone = "1.0.17"
rayon = "1.7"

# metrics
metrics = "0.22.0"
metrics-exporter-prometheus = { version = "0.14.0", default-features = false }
metrics-util = "0.16.0"
metrics-process = "2.0.0"

# proc-macros
proc-macro2 = "1.0"
quote = "1.0"

# misc-testing
proptest = "1.4"
proptest-derive = "0.4"
serial_test = "3"

# rpc
jsonrpsee = "0.23"
jsonrpsee-core = "0.23"
jsonrpsee-types = "0.23"
jsonrpsee-http-client = "0.23"

# http
http = "1.0"

# crypto
secp256k1 = { version = "0.28", default-features = false, features = [
    "global-context",
    "recovery",
] }
