[package]
name = "handshake"
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
prost.workspace = true
prost-types.workspace = true
libp2p.workspace = true
libp2p-stream.workspace = true

[build-dependencies]
prost-build = "0.12.6"
