[package]
name = "waku-swarm-relay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(not(target_arch = "wasm32"))'.bin]
path = "src/main.rs"

[dependencies]
once_cell = { workspace = true }
dotenv = { workspace = true }
clap = { workspace = true }
chrono = { workspace = true }
hex = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
ethers-core = { workspace = true }
ethers-contract = { workspace = true }
ethers-signers = { workspace = true }
url = "2.5.0"
anyhow = { workspace = true }
thiserror = { workspace = true }
waku-bindings = { git = "https://github.com/waku-org/waku-rust-bindings" }
reqwest = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true}
num-traits = "0.2.19"
logging = { path = "../../crates/logging" }
