[package]
name = "nectar-primitives"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Common types in Ethereum Swarm"

[dependencies]
alloy.workspace = true
nectar-primitives-traits.workspace = true

# misc
bytes.workspace = true
anyhow.workspace = true
thiserror.workspace = true

thread_local = "1.1.8"
rayon = "1.10.0"

# rand
rand = { workspace = true, optional = true, features = ["getrandom"] }

# tokio
tokio = { workspace = true, features = ["sync"] }
futures.workspace = true

# serde
serde.workspace = true

[dev-dependencies]
criterion = { workspace = true, features = ["async_tokio"] }
rand = { workspace = true, features = ["getrandom"] }
tokio = { workspace = true, features = ["full"] }

[build-dependencies]
alloy.workspace = true

[[bench]]
name = "primitives"
path = "benches/primitives.rs"
harness = false
required-features = ["rand"]

[[bench]]
name = "proofs"
path = "benches/proofs.rs"
harness = false
