[package]
name = "beers-primitives"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true
description = "Commonly used types in Beers"

[lints]
workspace = true

[dependencies]
## beers
bee_api = { git = "https://github.com/rndlabs/bee-api-rs.git" }

## ethereum
alloy-primitives = { workspace = true, features = ["rand"] }
alloy-signer = { workspace = true }
alloy-signer-wallet = { workspace = true }

libp2p.workspace = true

## async
tokio.workspace = true

## tracing
tracing.workspace = true

## misc
once_cell.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
num_enum = { version = "0.7", default-features = false }
strum = { version = "0.26", default-features = false, features = ["derive"] }

[dev-dependencies]
test-case = "3.3.1"
