[package]
name = "swarm"
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
alloy.workspace = true
libp2p.workspace = true

once_cell.workspace = true
thiserror.workspace = true
tokio.workspace = true