[package]
name = "swarm-wasm-lib"
version = "0.1.0"
authors = ["mfw78 <mfw78@rndlabs.xyz>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
bmt = { path = "../../crates/bmt" }
postage = { path = "../../crates/postage" }
js-sys = { workspace = true }
web-sys = { version = "0.3.64", features = ['console'] }
hex = { workspace = true }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

[dev-dependencies]
wasm-bindgen-test = { workspace = true }

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
