[package]
name = "builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
## beers
beers-node-core = { workspace = true }
beers-tracing = { workspace = true }
beers-tasks = { workspace = true }

## async 
futures.workspace = true
tokio = { workspace = true, features = [
    "sync",
    "macros",
    "time",
    "rt-multi-thread",
] }
tokio-stream.workspace = true

## misc
eyre = { workspace = true }

[lints]
workspace = true
