[package]
name = "wasm-playground"
version = "0.1.0"
authors = ["The wasm-bindgen Developers"]
edition = "2018"
rust-version = "1.56"

[lib]
crate-type = ["cdylib"]

[dependencies]
## beers
beers-primitives = { workspace = true }
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
alloy-signer-wallet.workspace = true
alloy-primitives.workspace = true
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
console_error_panic_hook = "0.1.7"
tracing-wasm = "0.2.1"
rand = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dependencies.web-sys]
version = "0.3.69"
features = [
    'Document',
    'Element',
    'HtmlElement',
    'Node',
    'Window',
    'File',
    'FileReader',
    'FileList',
    'HtmlDivElement',
    'HtmlInputElement',
    'HtmlTextAreaElement',
    'Event',
    'HtmlButtonElement'
]