[package]
name = "wasm-playground"
version = "0.1.0"
authors = ["The wasm-bindgen Developers"]
edition = "2018"
rust-version = "1.56"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.87"
bmt = { path = "../../crates/bmt" }
hex = { workspace = true }
console_error_panic_hook = "0.1.7"
tracing-wasm = "0.2.1"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dependencies.web-sys]
version = "0.3.64"
features = [
    'Document',
    'Element',
    'HtmlElement',
    'Node',
    'Window',
    'File',
    'FileReader',
    'FileList',
    'HtmlDivElement',
    'HtmlInputElement',
    'Event',
    'HtmlButtonElement'
]